config/routes.rb
Rails.application.routes.draw do
  resources :themes
  root to: 'pages#home'

  devise_for :users

  resources :users, only: [:show]
  resources :events

  resources :profiles, only: [:new, :edit, :create, :update]

  resources :events do
    resources :rsvps, only: [:create]
  end

  resources :photos, only: [:destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :themes

  validates :description, presence: true, length: { maximum: 500 }
  validates :name, :starts_at, :ends_at, presence: true

  has_many :rsvps, dependent: :destroy

  has_many :photos
  # validates :ends_at, presence: true #, #date: {after: :start_date}


#  validates_presence_of :start_date, :end_date
#
# validate :end_date_is_after_start_date
#
#
# #######
# private
# #######
#
# def end_date_is_after_start_date
#   return if end_date.blank? || start_date.blank?
#
#   if end_date < start_date
#     errors.add(:end_date, "cannot be before the start date")
#   end

  def bargain?
    price < 2
  end




  def self.order_by_price
    order :price
  end


  def available?(arrival, departure)
    rsvps.each do |rsvp|
      if (rsvp.starts_at <= departure) && (rsvp.ends_at >= arrival)
        return false
      end
    end

    true
  end

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :first_name, :last_name, :bio, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end


  def self.by_initial(letter)
    where("first_name LIKE ?", "#{letter}%").order(:first_name)
  end


end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
  belongs_to :user
  belongs_to :event

  # def set_total_price
  #   self.price = event.price
  #   total_days = (ends_at.to_date - starts_at.to_date).to_i
  #   self.total = price * total_days
  # end

  before_save :set_price

  def set_price
    price = self.event.price
  end


  def event_available?
    event.available? starts_at. ends_at
  end 

end

app/models/theme.rb
class Theme < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_and_belongs_to_many :events
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events, dependent: :destroy

  has_one :profile

  def has_profile?
    profile.present? && profile.persisted?
  end

  def full_name
    profile.full_name
  end

  has_many :rsvps, dependent: :destroy
  has_many :rsvped_events, through: :rsvps, source: :event

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @events = current_user.events
  end

  def show
    @themes = @event.themes
    @photos = @event.photos
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      image_params.each do |image|
        @event.photos.create(image: image)
      end

      redirect_to edit_event_path(@event),
      notice: "Event successfully created"
    else
      render :new
    end
  end

  def edit
    if current_user.id == @event.user.id
      @photos = @event.photos
    else
      redirect_to root_path, notice: "You do not have persmission."
    end
  end

  def update
    if @event.update(event_params)
      image_params.each do |image|
        @event.photos.create(image: image)
      end

      redirect_to edit_event_path, notice: "Event successfully updated"
    else
      render :edit
    end
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :description, :location, :price, :capacity, :includes_food, :includes_drinks, :starts_at, :ends_at, :active, :user, theme_ids: [])
    end

    def image_params
      params[:images].present? ? params.require(:images) : []
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def destroy
    @photo = Photo.find(params[:id])
    @event = @photo.event
    if @event.user.id == current_user.id
      @photo.destroy

      redirect_to edit_event_path(@event), notice: "Photo was successfully removed"
    else
      redirect_to event, notice: "Sorry, photo cannot be removed at this time"
    end
  end
end

app/controllers/rsvp_controller.rb
class RsvpController < ApplicationController
  before_action :authenticate_user!

  def create
    @rsvp = current_user.rsvps.new(rsvp_params)
    @rsvp.event_id = params[:event_id]

    if @rsvp.event_available?
       @rsvp.set_total_price
       @rsvp.save
       redirect_to @rsvp.event, notice: "Thank you for rsvp-ing!"

    else
      redirect_to @rsvp.event, notice: "Sorry! This listing is not available during the dates you requested."
    end
  end


  private


  ########## MOVED TO APP/MODELS/RSVP.RB - FAT MODELS, SKINNY CONTROLLERS #########
  # def get_total_price(rsvp_params)
  #   arrival, departure = get_dates(rsvp_params)
  #
  #   total_days = (departure - arrival).to_i
  #   rsvp_params[:price].to_i * total_days
  # end
  #
  # def get_dates(rsvp_params)
  #   arrival = Date.new(rsvp_params["starts_at(1i)"].to_i,
  #                      rsvp_params["starts_at(2i)"].to_i,
  #                      rsvp_params["starts_at(3i)"].to_i)
  #
  #
  #   departure = Date.new(rsvp_params["ends_at(1i)"].to_i,
  #                        rsvp_params["ends_at(2i)"].to_i,
  #                        rscp_params["ends_at(3i)"].to_i)
  #
  #   return arrival, departure
  # end

  def rsvp_params
    params.require(:rsvp).permit(:starts_at, :ends_at)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/rsvp_helper.rb
module RsvpHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodaisseurUp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'shared/navbar' %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/home.html.erb
<div class="header">
  <h1>CodaisseurUp</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>

<!-- <div class="navigation section_1">
  <h3>latest events</h3>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique laborum, eveniet asperiores vitae praesentium doloremque totam error, quia inventore doloribus, eligendi ea earum commodi vel aut dolor. Assumenda, obcaecati, quas!</p>
  <div class="row">
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src="..." alt="...">
        <div class="caption">
          <h3>Thumbnail label</h3>
          <p>...</p>
          <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="navigation section_2">
  <h3>find an event</h3> -->

</div>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "CodaisseurUp", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= current_user.has_profile? ? current_user.full_name : current_user.email %> 
              <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <li><%= link_to "Your Listings", events_path %></li>
              <li role="separator" class="divider"></li>
              <% if current_user.has_profile? %>
              <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
              <% else %>
              <li><%= link_to "Create Profile", new_profile_path %></li>
              <% end %>
              <li><%= link_to "Edit Password", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>