config/routes.rb
Rails.application.routes.draw do
  resources :themes
  root to: 'pages#home'

  devise_for :users

  resources :users, only: [:show]
  resources :events

  resources :profiles, only: [:new, :edit, :create, :update]

  resources :events do
    resources :rsvps, only: [:create]
  end

  resources :photos, only: [:destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :themes

  validates :description, presence: true, length: { maximum: 500 }
  validates :name, :starts_at, :ends_at, presence: true

  has_many :rsvps, dependent: :destroy

  has_many :photos
  # validates :ends_at, presence: true #, #date: {after: :start_date}


#  validates_presence_of :start_date, :end_date
#
# validate :end_date_is_after_start_date
#
#
# #######
# private
# #######
#
# def end_date_is_after_start_date
#   return if end_date.blank? || start_date.blank?
#
#   if end_date < start_date
#     errors.add(:end_date, "cannot be before the start date")
#   end

  def bargain?
    price < 2
  end




  def self.order_by_price
    order :price
  end


  def available?(arrival, departure)
    rsvps.each do |rsvp|
      if (rsvp.starts_at <= departure) && (rsvp.ends_at >= arrival)
        return false
      end
    end

    true
  end

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :first_name, :last_name, :bio, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end


  def self.by_initial(letter)
    where("first_name LIKE ?", "#{letter}%").order(:first_name)
  end


end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
  belongs_to :user
  belongs_to :event

  # def set_total_price
  #   self.price = event.price
  #   total_days = (ends_at.to_date - starts_at.to_date).to_i
  #   self.total = price * total_days
  # end

  before_save :set_price

  def set_price
    price = self.event.price
  end


  def event_available?
    event.available? starts_at. ends_at
  end 

end

app/models/theme.rb
class Theme < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_and_belongs_to_many :events
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events, dependent: :destroy

  has_one :profile

  def has_profile?
    profile.present? && profile.persisted?
  end

  def full_name
    profile.full_name
  end

  has_many :rsvps, dependent: :destroy
  has_many :rsvped_events, through: :rsvps, source: :event

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @events = current_user.events
  end

  def show
    @themes = @event.themes
    @photos = @event.photos
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      image_params.each do |image|
        @event.photos.create(image: image)
      end

      redirect_to edit_event_path(@event),
      notice: "Event successfully created"
    else
      render :new
    end
  end

  def edit
    if current_user.id == @event.user.id
      @photos = @event.photos
    else
      redirect_to root_path, notice: "You do not have persmission."
    end
  end

  def update
    if @event.update(event_params)
      image_params.each do |image|
        @event.photos.create(image: image)
      end

      redirect_to edit_event_path, notice: "Event successfully updated"
    else
      render :edit
    end
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :description, :location, :price, :capacity, :includes_food, :includes_drinks, :starts_at, :ends_at, :active, :user, theme_ids: [])
    end

    def image_params
      params[:images].present? ? params.require(:images) : []
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def destroy
    @photo = Photo.find(params[:id])
    @event = @photo.event
    if @event.user.id == current_user.id
      @photo.destroy

      redirect_to edit_event_path(@event), notice: "Photo was successfully removed"
    else
      redirect_to event, notice: "Sorry, photo cannot be removed at this time"
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

   def new
     @profile = Profile.new
   end

   def create
     @profile = current_user.build_profile(profile_params)

     if @profile.save
       redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
     else
       render :new
     end
   end

   def edit
   end

   def update
     if @profile.update(profile_params)
       redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
     else
       render :edit
     end
   end

   private
     def set_profile
       @profile = current_user.profile
     end

     def profile_params
       params.require(:profile).permit(:first_name, :last_name, :bio)
     end

end

app/controllers/rsvp_controller.rb
class RsvpController < ApplicationController
  before_action :authenticate_user!

  def create
    @rsvp = current_user.rsvps.new(rsvp_params)
    @rsvp.event_id = params[:event_id]

    if @rsvp.event_available?
       @rsvp.set_total_price
       @rsvp.save
       redirect_to @rsvp.event, notice: "Thank you for rsvp-ing!"

    else
      redirect_to @rsvp.event, notice: "Sorry! This listing is not available during the dates you requested."
    end
  end


  private


  ########## MOVED TO APP/MODELS/RSVP.RB - FAT MODELS, SKINNY CONTROLLERS #########
  # def get_total_price(rsvp_params)
  #   arrival, departure = get_dates(rsvp_params)
  #
  #   total_days = (departure - arrival).to_i
  #   rsvp_params[:price].to_i * total_days
  # end
  #
  # def get_dates(rsvp_params)
  #   arrival = Date.new(rsvp_params["starts_at(1i)"].to_i,
  #                      rsvp_params["starts_at(2i)"].to_i,
  #                      rsvp_params["starts_at(3i)"].to_i)
  #
  #
  #   departure = Date.new(rsvp_params["ends_at(1i)"].to_i,
  #                        rsvp_params["ends_at(2i)"].to_i,
  #                        rscp_params["ends_at(3i)"].to_i)
  #
  #   return arrival, departure
  # end

  def rsvp_params
    params.require(:rsvp).permit(:starts_at, :ends_at)
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/rsvp_helper.rb
module RsvpHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: { multipart: true } do |f| %>
  <div class="form-group">
    <label>Name</label>
    <%= f.text_area :name, placeholder: "Event name", class: "form-control"%>
  </div>

  <div class="form-group">
    <label>Description</label>
    <%= f.text_area :description, rows: 5, placeholder: "Say something about your awesome event", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Location</label>
    <%= f.text_area :location, placeholder: "Location", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Price</label>
    <%= f.select :price, [["0", 0], ["1", 1], ["2", 2], ["3", 3], ["4", 4], ["5+", 5]], prompt: "Select a price", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Capacity</label>
    <%= f.select :capacity, [["10", 10], ["20", 20], ["30", 30], ["40+", 40]], prompt: "Select a capacity", class: "form-control" %>
  </div>



  <label>Amenities</label>

  <div class="form-group">
    <%= f.check_box :includes_food %> Food
  </div>
  <div class="form-group">
    <%= f.check_box :includes_drinks %> Drinks
  </div>


  <div class="form-group">
    <label>Starts At</label>
    <div class="input-group">
      <div class="input-group-addon"></div>
      <%= f.datetime_select :starts_at, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label>Ends At</label>
    <div class="input-group">
      <div class="input-group-addon"></div>
      <%= f.datetime_select :ends_at, class: "form-control" %>
    </div>
  </div>

  <label>Themes</label>

  <%= f.collection_check_boxes(:theme_ids, Theme.all, :id, :name) do |b| %>
  <div class="form-group">
    <%= b.check_box(class: "check_box") %> <%= b.object.name %>
  </div>
  <% end %>

  <label>Photos</label>

  <div class="form-group">
    <span class="btn btn-default">
      Upload Photos
      <%= file_field_tag "images[]", type: :file, mutliple: true %>
    </span>
  </div>

  <div id="photos">
    <%= render 'photos/list' %>
  </div>

  <label>Do you wish to publish your awesome event?</label>

  <div class="form-group">
    <%= f.check_box :active %> Active
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit your event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", events_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", events_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Your Listings
      </div>
      <div class="panel-body">

        <% @events.each do |event| %>
        <div class="row">
          <div class="col-md-7">
            <h4><%= event.name %></h4>
          </div>
          <div class="col-md-3 right">
            <%= link_to "View", event, class: "btn btn-default" %>
            <%= link_to "Update", edit_event_path(event), class: "btn btn-default" %>
          </div>
        </div>
        <% end %>

      </div>
    </div>

    <%= link_to "Add new event", new_event_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/events/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add an awesome event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<!-- Rsvp form -->
<% if current_user != @event.user %>
  <div class="panel panel-primary">
    <div class="panel-heading">Rsvp for this event</div>
    <div class="panel-body">
      <%= render 'rsvps/form' %>
    </div>
  </div>
<% end %>


<div class="panel panel-primary">
  <div class="panel-heading"><%= @event.name %></div>

  <div class="panel-body">

    <p>Location: <%= @event.location %></p>
    <p>Host: <%= @event.user.email %></p>

    <!-- Main Info -->
    <h4>Main Info</h4>
    <p>Event Type: <%= @event.name %></p>
    <p><%= @event.capacity %> <%= @event.capacity > 1 ? "Guests" : "Guest" %></p>

    <!-- About -->
    <h4>About</h4>
    <p><%= @event.description %></p>

    <!-- Amenities -->
    <h4>Amenities</h4>
    <ul class="amenities">
      <li><%= !@event.includes_food ? ("<s>Food</s>").html_safe : "Food" %></li>
      <li><%= !@event.includes_drinks ? ("<s>Drinks</s>").html_safe : "Drinks" %></li>
    </ul>

    <!-- Themes -->
    <h4>Themes</h4>
    <% @themes.each do |theme| %>
    <span class="label label-success"><%= theme.name %></span>
    <% end %>

    <!-- Photos -->
    <h4>Photos</h4>
    <% @event.photos.each do |photo| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= image_tag photo.image.thumbnail %>
      </div>
    </div>
    <% end %>

  </div>

</div>

<%= link_to "Back", events_path, class: "btn btn-default" %>

app/views/photos/_list.html.erb
<% if @photos %>
  <% @photos.each do |photo| %>
    <div class="panel panel-default">
      <div class="panel-heading preview">
        <%= image_tag photo.image.thumbnail %>
      </div>
      <div class="panel-body">
        <%= link_to "Delete", photo_path( photo.id ),
        class: "btn btn-default", method: :delete,
        data: { confirm: "Are you sure?" } %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
  <% @profile.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger"><%= msg %></p>
  <% end %>

  <div class="form-group">
    <label>First Name</label>
    <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Bio</label>
    <%= f.text_area :bio, rows: 5, placeholder: "Say something about yourself", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Back", root_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Edit your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Create your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/rsvps/_form.html.erb
<%= form_for [@event, @event.rsvps.new] do |f| %>
  <p><strong>Price</strong> <span>€</span> <%= @event.price %></p>

  <hr>

  <div class="form-group">
    <label>Starting Time</label>
    <%= f.date_select :starts_at %>
  </div>

  <div class="form-group">
    <label>Ending Time</label>
    <%= f.date_select :ends_at %>
  </div>

<!-- NOT NEEDED ANYMORE -->
  <!-- <%= f.hidden_field :event_id, value: @event.id %>
  <%= f.hidden_field :price, value: @event.price %> -->

  <hr>

  <div class="actions">
    <%= f.submit "Rsvp Now", class: "btn btn-success" %>
  </div>
<% end %>